# Generated by Django 4.2.7 on 2024-01-22 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_comment_comment_user_comment_post"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comment",
            name="user_comment_post",
        ),
    ]
