# Generated by Django 4.2.7 on 2024-01-28 12:20

import DjangoGramm.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_photo_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="picture",
            field=models.ImageField(
                upload_to=functools.partial(
                    DjangoGramm.utils.directory_path, *(), **{"base_folder": "pictures"}
                )
            ),
        ),
    ]
