# Generated by Django 4.2.7 on 2023-11-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
