# Generated by Django 4.2.7 on 2023-11-24 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
