# Generated by Django 4.2.7 on 2023-11-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_like_post_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(blank=True, to="posts.hashtag"),
        ),
    ]
