# Generated by Django 4.2.7 on 2023-11-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_hashtag_post_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
