# Generated by Django 4.2.7 on 2024-01-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                default="remake@me.com",
                max_length=254,
                verbose_name="email address",
            ),
            preserve_default=False,
        ),
    ]
