# Generated by Django 4.2.7 on 2024-01-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True, unique=True
            ),
        ),
    ]
