# Generated by Django 4.2.7 on 2024-01-25 14:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="avatar"
            ),
        ),
    ]
